Repository mattermost/mattermost-plugin-api, pull requests merged in 2021-07, with the labels that each got.

#96 MM-32421: Extend channel sidebar category APIs for PluginAPI
  channel.go
  channel_test.go
  go.mod
  go.sum
Labels: 3: QA Review

#95 [MM-36664] Added plugin API methods for user access tokens and OAuth apps
  client.go
  go.mod
  go.sum
  oauth.go
  user.go
Labels: 4: Reviews Complete

#97 [MM-2307] Move helpers from server repo into plugin api one
  bot.go
  botensure.go
  client.go
  configuration.go
  configuration_test.go
  experimental/bot/bot.go
  kv.go
  kv_test.go
  plugin_test.go
  plugins.go
  post.go
  post_test.go
  system.go
  tests/testplugin.tar.gz
  utils.go
  utils_test.go
Labels: 4: Reviews Complete

#98 Revert "Add DB RPC API support to client (#93)"
  bot_test.go
  channel_test.go
  client.go
  configuration_test.go
  emoji_test.go
  example_client_test.go
  experimental/bot/poster/default_poster_test.go
  file_test.go
  go.mod
  go.sum
  kv_test.go
  logrus_test.go
  plugin_test.go
  post_test.go
  store.go
  store_test.go
  system_test.go
  team_test.go
  user_test.go
Labels: 4: Reviews Complete

#99 Revert "Revert "Add DB RPC API support to client (#93)" (#98)"
  bot_test.go
  channel_test.go
  client.go
  configuration_test.go
  emoji_test.go
  example_client_test.go
  experimental/bot/poster/default_poster_test.go
  file_test.go
  go.mod
  go.sum
  kv_test.go
  logrus_test.go
  plugin_test.go
  post_test.go
  store.go
  store_test.go
  system_test.go
  team_test.go
  user_test.go
Labels: 4: Reviews Complete

#100 [MM-37314] Fix categorization method version
  channel.go
Labels: 2: Dev Review
